# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ad2995ef4496fb0a8d469e77cde81e9c45363dd8536fdc757d92e8d49647efcddb801ac0a0d6c6c4689addc83f0051ddcd0de200a0a8885cbcb438955323e1f

test:
  secret_key_base: 273d1a890cb5d4cd7407861241f894ae748e05621bd5f025e5e3e02e561faae420356b252f183790261b49681f2f3e542820a5422d710a6edcd536df6fb8daa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
